### ISSUE TITLE
Uncaught TypeError: window.setGameMode is not a function

### ISSUE THREAD

**Issue by DaAwesomeRazor** [xzfc/agar-expose#11]
Sorry for posting so many issues. IM working on an extension. ANyways, i m getting this error once in a while. It causes a white screen

**Comment by xzfc** [comment]
I know about this bug. Workaround for now is pressing `Ctrl+F5` when it happens.
I think, it is caused by https://github.com/Tampermonkey/tampermonkey/issues/211.
