### ISSUE TITLE
Dimensions[] no longer returns accurate data

### ISSUE THREAD

**Issue by jakemayeux** [xzfc/agar-expose#13]
The coordinates are relative to the player's position

**Comment by u624ka** [comment]
The coordinates are still accurate and absolute except now they are not of the entire playfield, but of a rectangle centered at the player's position, and are in a randomly shifted coordinate system.

**Comment by jakemayeux** [comment]
Yes, I've noticed. I made a change to the wiki

**Comment by xzfc** [comment]
Closing since I will not fix this.
Expose should be as dumb as possible to make its maintaining easy.
All complex logic to detect actual world borders' coordinates should be inside scripts using expose.
