### ISSUE TITLE
dimensions hook

### ISSUE THREAD

**Issue by henopied** [xzfc/agar-expose#15]
Would it be possible to make a hook for case 64 so I could get a callback that would be called every time opcode 64 gets sent.

**Comment by mbm3** [comment]
same, tried adding a hook, and never got the callback after pressing play.

**Comment by xzfc** [comment]
Sure, `window.agar.hooks.dimensionsUpdated(minX, minY, maxX, maxY)` added.

**Comment by henopied** [comment]
Thanks, you made my day :)

**Comment by mbm3** [comment]
:D
