### ISSUE TITLE
Not working with extensions

### ISSUE THREAD

**Issue by SrNicolas** [xzfc/agar-expose#20]
Ifk if it's me por This conde Can't work with extensions, because I tried and got no luck making this work IN A Google chrome extenaion

**Comment by mbm3** [comment]
It's easy

**Comment by SrNicolas** [comment]
wan't to help? cuz I just cant get it to work

**Comment by HackMeThat** [comment]
// manifest.json
`{
  "manifest_version": 2,
  "name": "Expose",
  "version": "0.1",
  "browser_action": {
  "default_title": "Expose"
  },  
  "content_scripts": [
    {
      "matches": ["http://agar.io/*"],
      "js": ["content.js" ],
      "run_at": "document_start"
    }
  ],
  "web_accessible_resources": [ "expose.js"]
}`

//expose.js

```
(function() {

// Paste https://github.com/xzfc/agar-expose/blob/master/expose.user.js code here

window.onerror = function(msg) {
if(msg=='Uncaught TypeError: window.setGameMode is not a function'){window.location.reload();}
    return true;
}
}())
```

// content.js
`var s = document.createElement('script');
s.src = chrome.extension.getURL('expose.js');
s.onload = function() {
        this.parentNode.removeChild(this);
};
(document.head||document.documentElement).appendChild(s);`
