### ISSUE TITLE
Needs another update

### ISSUE THREAD

**Issue by ZfsrGhS953** [xzfc/agar-expose#23]
Agar.io has updated now, some things in agar-expose are broken now.

**Comment by wartoz** [comment]
yeah

**Comment by ZfsrGhS953** [comment]
main_out.js was renamed to agario.core.js, but even if you change that it won't fix things

**Comment by ZfsrGhS953** [comment]
I think version number also changed from 2200049715 to something else.

**Comment by mbm3** [comment]
What has changed?? (I'm at school can't check atm)

**Comment by TheJustExper** [comment]
lOL MASON

**Comment by TheJustExper** [comment]
Hey mason

**Comment by easyrider81** [comment]
get these errors in console

<a href="https://gyazo.com/77d9811c84c69a04eea26b86ef0d4f00"><img src="https://i.gyazo.com/77d9811c84c69a04eea26b86ef0d4f00.png" alt="https://gyazo.com/77d9811c84c69a04eea26b86ef0d4f00"/></a>

**Comment by xzfc** [comment]
That happened, new Agar client is very different from the old one, so using Expose on it is impossible.
I don't think that regex-replacement patch approach can be ever used on the new client.
So, if you wanna fix your mods, you should include full client source into it.

**Comment by LostCodesy** [comment]
@xzfc too need an update :(

**Comment by ZfsrGhS953** [comment]
It was rewritten in asm.js using Emscripten, so a fix wouldn't be simple. Agar-expose needs to be rewritten from scratch.
