### ISSUE TITLE
Agario-client 

### ISSUE THREAD

**Issue by Optimusprimeagario** [xzfc/agar-expose#29]
Agario client is outdated so its shows Minions: 1 or 2 but no minions/bots swaps is it agario-client or other problem please help by the way server.js is fixed is it because of new protocol

**Comment by Sonicmaster13** [comment]
PLEASE do not talk about davidmanns stuff here. If you need help, ask on his github page.

This is about Agario-Expose, not Agario-Client of Davidmanns client
