### ISSUE TITLE
"window.agar.allCells" Doesn't exist?

### ISSUE THREAD

**Issue by Tombez** [xzfc/agar-expose#30]
![mghmjfgj](https://cloud.githubusercontent.com/assets/17679570/15352266/385da26c-1c98-11e6-9ee2-ca67eb318d87.PNG)

**Comment by xzfc** [comment]
It became broken after big agar update.
Most of the wiki documentation page is outdated now.

**Comment by Tombez** [comment]
I see, that's unfortunate.
