### ISSUE TITLE
v72's website is down

### ISSUE THREAD

**Issue by NuclearC** [xzfc/agar-expose#37]
@xzfc can you please back it up or give me the out.html?

**Comment by idkRage** [comment]
yes it would be nice (NuclearC its me Rage ;))

**Comment by t11tanYT** [comment]
https://github.com/TrapKillo/trapclientv72

**Comment by xzfc** [comment]
http://dump.bitcheese.net/files/siwebed/out.html

>

**Comment by NuclearC** [comment]
holy shit! thank you very much! <3

**Comment by t11tanYT** [comment]
@NuclearC  xD

**Comment by Jhair2015** [comment]
nice :v
